os: osx
osx_image: xcode7.3
language: bash
before_install: 
  - if [ ! -d "$HOME/lame-3.99.5" ]; then
        curl -L -O http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz;
        tar -zxvf lame-3.99.5.tar.gz;
        cd lame-3.99.5;
        ./configure;
        make;
        sudo make install;
        cd ..;
    fi;
  - curl -L -O http://downloads.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2-macosx.zip
  - unzip sox-14.4.2-macosx.zip
  - mkdir voices
  - cd voices
  - curl -L -O http://swcdn.apple.com/content/downloads/31/08/031-11580/yl6kwlywi3fnk7dw5l440jya4w5x6cgrj4/MLV_en_US_samantha.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/25/38/031-11390/jyv1losfgofn70cfds6w9c2xxkj6ea1kgn/MLV_de_DE_anna.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/01/60/031-11670/i5e5pj4cn5oy6nr1z129d415t75pc11bmf/MLV_en_GB_daniel.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/47/22/031-11693/09kxdzz6urb2jhqd438daigpq93n0rxg1i/MLV_fr_FR_thomas.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/32/16/031-29337/rvz49jpfk09y3nmmh4w5ric4t0xfhzoyoo/MultiLingualVoice_fr_CA_amelie.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/38/34/031-11480/zm58e6jsllj40uehdcks7fkmds2i9o6iv5/MLV_en_AU_karen.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/12/30/031-11696/lea93eo0146c5o59vjy9kwa3v0xhnmt1wj/MLV_en_IE_moira.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/58/09/031-29381/elohs1hjm921a220ly2gzv5azdlm88cigy/MLVUpdate_en_scotland_fiona.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/37/45/031-29440/cy2gbk2fpbcppzt0qw7hr38equhkdd2ttf/MultiLingualVoice_en_US_tom.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/38/34/031-26101/pxikgehnvjg15s2p0jy9mcqpb5gjyuzl5k/MLVUpdate_en_US_allison.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/46/57/031-29409/etpbacnsq97v7tn7wiqrx0oaxkpkisnus9/MultiLingualVoice_en_GB_kate.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/35/59/031-29327/69eiok26zcl4y2uhj7b0g8c2rld9h9d2kp/MultiLingualVoice_fi_FI_satu.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/16/50/031-29399/2evmr1hmtkbuuoic6edb4fj8da1ciykbb8/MLVUpdate_fr_FR_audrey.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/47/23/031-29386/o0pr75tsoomqn2gksluga4bbcuao5ugdzv/MLVUpdate_fr_FR_aurelie.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/17/28/031-29436/4kxyz5vev9shy2f5guvkm8548rn1n0omhm/MultiLingualVoice_fr_CA_nicolas.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/24/02/031-29389/vbrwjp9ymfddlybmesnf66gyn6d5ni920z/MultiLingualVoice_el_GR_melina.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/03/47/031-29342/6tfr5l9uhpzsgeot3c4d7b2v3ir37royko/MultiLingualVoice_it_IT_luca.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/37/54/031-26084/000hk07x7imylighbkyodyvu95d86j5wdo/MultiLingualVoice_it_IT_alice.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/21/30/031-29330/5uuzcgvsskfoz1wgm9a7yuxgm50h3epxeg/MLVUpdate_nl_NL_xander.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/58/01/031-29360/b2urz5xj75gooi2x5j4yk7e8gwzd4y0hd9/MultiLingualVoice_no_NO_henrik.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/02/59/031-29433/3m53kd05d63arhhmx8ij7qsq0fc9j5hq0q/MLVUpdate_no_NO_nora.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/51/60/031-29407/xdvm4f1nskojvn63ejp5mdrpoggbbnu7ul/MLVUpdate_pl_PL_zosia.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/09/29/031-29396/nqds1hns6fg2o66t8snbdeshv7dc2tquct/MLVUpdate_pt_PT_joana.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/57/38/031-29322/ayn7w001cza2u0hk6b84qlijz2e2fd4sjt/MLVUpdate_ru_RU_yuri.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/33/19/031-22904/guq65rotjmmke277rz94q5qsiwsxbycwkc/MLVUpdate_ru_RU_milena.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/26/04/031-11476/rj3hkevk8u7p1me4epmf12q4gca1tk37rq/MLV_sv_SE_alva.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/25/25/031-11383/iuyu10lmznf19emz1e6l3fsqjypwb3ke7y/MLV_sk_SK_laura.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/39/32/031-26124/dxwxcovmkxsa9u0fsvb29lavsg8lh9ruc0/MLVUpdate_es_ES_jorge.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/55/31/031-29426/w0067w2wo6vs7mpn03zqykivkkr4ldnqcs/MultiLingualVoice_es_ES_monica.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/01/22/031-11566/4yqsqbld0c4tnfn8bdd2r9bpps6yyobhbl/MLV_cs_CZ_zuzana.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/55/11/031-29425/c6z0kqtv3c9k2qpfi6xu4dc5n83niaqtbh/MLVUpdate_tr_TR_yelda.pkg
  - curl -L -O http://swcdn.apple.com/content/downloads/32/23/031-29395/jvbvx3mcg63afdlsvvp5c2b6kc8myt1k3v/MLVUpdate_hu_HU_mariska.pkg
  - for f in *.pkg ; do sudo installer -pkg "$f" -target / ; done
  - cd ..

script: 
  - cd genspeech
  - if [ "$TRAVIS_EVENT_TYPE" == "api" ]; then
       curl https://moeder.pythonanywhere.com/voicepacker/default/deliver/${BUILD_ID} > modelAlert${BUILD_ID}.txt-mac;
       tr -d '\r' < modelAlert${BUILD_ID}.txt-mac > modelAlert${BUILD_ID}.txt;
       echo >> modelAlert${BUILD_ID}.txt;
       ./genspeech $GLOBAL_LANG $VOICE $BUILD_ID $NAME $SPEED;
    fi;
  - say -v ?
  - ls /System/Library/Speech/Voices/
  - cd ..
after_success:
  - ./push.sh
