os: osx
osx_image: xcode7.3
language: bash
before_install: 
  - if [ ! -d "$HOME/lame-3.99.5" ]; then
        curl -L -O http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz;
        tar -zxvf lame-3.99.5.tar.gz;
        cd lame-3.99.5;
        ./configure;
        make;
        sudo make install;
        cd ..;
    fi;
  - curl -L -O http://downloads.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2-macosx.zip
  - unzip sox-14.4.2-macosx.zip
  - ./get_language_pack.sh $VOICE

script: 
  - cd genspeech
  - if [ "$TRAVIS_EVENT_TYPE" == "api" ]; then
       curl https://moeder.pythonanywhere.com/voicepacker/default/deliver/${BUILD_ID} > modelAlert${BUILD_ID}.txt-mac;
       tr -d '\r' < modelAlert${BUILD_ID}.txt-mac > modelAlert${BUILD_ID}.txt;
       echo >> modelAlert${BUILD_ID}.txt;
       ./genspeech $GLOBAL_LANG $VOICE $BUILD_ID $NAME $SPEED;
    fi;
  - say -v ?
  - ls /System/Library/Speech/Voices/
  - cd ..
after_success:
  - if [ "$TRAVIS_EVENT_TYPE" == "api" ]; then
       ./push.sh
    fi;
