os: osx
language: bash
cache: bundle 
before_install: brew update
install: 
  - brew install lame
script: 
  - cd genspeech
  - if [ "$TRAVIS_EVENT_TYPE" == "api" ]; then
       curl https://moeder.pythonanywhere.com/voicepacker/default/deliver/${BUILD_ID} > modelAlert${BUILD_ID}.txt-mac;
       tr '\r' '\n' < modelAlert${BUILD_ID}.txt-m > modelAlert${BUILD_ID}.txt;
       ./genspeech $GLOBAL_LANG $VOICE $BUILD_ID;
    else
       ./genspeech EN Alex EN;
    fi;
  - cd ..
  - say -v ?
before_deploy:
  - mkdir release/
  - mv genspeech/*.zip release/
  - cp iopage/* release/
  - cd release && ../create_index.sh && cd ..
deploy:
  provider: pages
  repo: TheRealMoeder/TheRealMoeder.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: release
  on:
    branch: master
